// Member types
export type MembershipType = 'Day Pass' | 'Warrior Pass' | 'Gladiator Pass' | 'Alpha Elite Pass';
export type MemberStatus = 'Active' | 'Expired';

export interface Member {
  id: string;
  name: string;
  contact: string;
  membershipType: MembershipType;
  startDate: string;
  expiryDate: string;
  status: MemberStatus;
  createdAt: Date;
  updatedAt: Date;
}

// Walk-in types
export type PaymentMethod = 'Cash' | 'GCash' | 'Bank Transfer' | 'Credit Card';

export interface WalkIn {
  id: string;
  name: string;
  date: Date;
  payment: number;
  method: PaymentMethod;
  createdAt: Date;
}

// Inventory types
export interface InventoryItem {
  id: string;
  productName: string;
  price: number;
  stock: number;
  createdAt: Date;
  updatedAt: Date;
}

// Cashflow types - UPDATED with more specific sources
export type CashflowType = 'income' | 'expense';
export type IncomeSource = 'Day Pass' | 'Warrior Pass' | 'Gladiator Pass' | 'Alpha Elite Pass' | 'Product Sale';
export type ExpenseSource = 'Rent' | 'Utilities' | 'Salaries' | 'Maintenance' | 'Equipment' | 'Marketing' | 'Other';

// Enhanced cashflow entry with detailed tracking
export interface CashflowEntry {
  id: string;
  type: CashflowType;
  source: IncomeSource | ExpenseSource;
  amount: number;
  date: string;
  notes: string;
  
  // Enhanced tracking fields
  linkedId?: string; // Member ID, Walk-in ID, Sale ID, etc.
  linkedType?: 'member' | 'walkin' | 'sale' | 'expense'; // What type of record this links to
  membershipType?: MembershipType; // For membership payments
  productName?: string; // For product sales
  customerName?: string; // Customer/member name
  paymentMethod?: PaymentMethod; // How it was paid
  
  // Auto-generated flag to distinguish from manual entries
  autoGenerated: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

// Sale entry for store transactions
export interface SaleEntry {
  id: string;
  items: SaleItem[];
  totalAmount: number;
  paymentMethod: PaymentMethod;
  customerName: string;
  date: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface SaleItem {
  productId: string;
  productName: string;
  price: number;
  quantity: number;
  subtotal: number;
}

// Member payment tracking - NEW
export interface MemberPayment {
  id: string;
  memberId: string;
  memberName: string;
  membershipType: MembershipType;
  amount: number;
  paymentMethod: PaymentMethod;
  paymentDate: string;
  period: string; // e.g., "January 2024" or "Jan 15 - Feb 15, 2024"
  notes?: string;
  
  // Link to cashflow entry
  cashflowId?: string;
  
  createdAt: Date;
  updatedAt: Date;
}

// Dashboard stats types
export interface DashboardStats {
  totalMembers: number;
  activeMembers: number;
  todayWalkIns: number;
  monthlyIncome: number;
  monthlyExpenses: number;
  netProfit: number;
  membershipBreakdown: {
    warrior: number;
    gladiator: number;
    alphaElite: number;
  };
}

// Form types - UPDATED
export interface MemberForm {
  name: string;
  contact: string;
  membershipType: MembershipType;
  startDate: string;
  expiryDate?: string; // Optional for auto-calculated types
}

// New payment form for members
export interface MemberPaymentForm {
  memberId: string;
  amount: number;
  paymentMethod: PaymentMethod;
  paymentDate: string;
  period?: string;
  notes?: string;
}

export interface WalkInForm {
  name: string;
  payment: number;
  method: PaymentMethod;
}

export interface InventoryForm {
  productName: string;
  price: number;
  stock: number;
}

export interface ExpenseForm {
  source: ExpenseSource;
  amount: number;
  date: string;
  notes: string;
}